#spring:
#  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/mention
#    username: root
#    password: root
#
#jpa:
#  show-sql: true
#  hibernate:
#    ddl-auto: create
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MariaDBDialect
#  generate-ddl: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/mention?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


jwt:
  secret:
    key: r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E

springboot:
  jwt:
    secret: flature!@#

