// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecbSTYv3EIYnYUV4rSDch2s3cjnvUpWY',
    appId: '1:527659727497:android:d928d1bf083c535c83a458',
    messagingSenderId: '527659727497',
    projectId: 'flufire-s',
    storageBucket: 'flufire-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHI0kYHnvf0_s_HCvi9pvHj6_zWeYhVy8',
    appId: '1:527659727497:ios:c46e9eedcc1ed33a83a458',
    messagingSenderId: '527659727497',
    projectId: 'flufire-s',
    storageBucket: 'flufire-s.appspot.com',
    androidClientId:
        '527659727497-s25q2kq8vcfdsh77347qp7gf1ddv7qk3.apps.googleusercontent.com',
    iosClientId:
        '527659727497-c5mu7q8k66a444fohdnco7t16jvn3tin.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluTest002',
  );
}
