server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: k8c1051.p.ssafy.io
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/login
          filters:
            - CustomFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - CustomFilter
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team-service/**
          filters:
            - CustomFilter
        - id: topic-service
          uri: lb://TOPIC-SERVICE
          predicates:
            - Path=/topic-service/**
          filters:
            - CustomFilter
            - AuthorizationHeaderFilter
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, busrefresh, httptrace



